[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
autobins = false
default-run = "xtask"

[features]
default = []
engine-tools = [
    "dep:clonk-engine",
    "dep:clonk-logging",
    "dep:clonk-resources",
    "dep:tracing",
    "dep:walkdir",
    "dep:zip",
]

[dependencies]
anyhow = "1"
walkdir = { version = "2", optional = true }
zip = { version = "0.6", default-features = false, features = ["deflate"], optional = true }
clonk-engine = { path = "../crates/clonk-engine", optional = true }
clonk-logging = { path = "../crates/clonk-logging", optional = true }
clonk-resources = { path = "../crates/clonk-resources", optional = true }
tracing = { version = "0.1", optional = true }

[lib]
doctest = false

[[bin]]
name = "xtask"
path = "src/dispatcher.rs"
test = false

[[bin]]
name = "xtask-engine-tools"
path = "src/main.rs"
required-features = ["engine-tools"]
test = false
