[package]
name = "clonk-launcher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0"
clonk-core = { path = "../clonk-core" }
clonk-platform = { path = "../clonk-platform" }
clonk-resources = { path = "../clonk-resources" }
open = "5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
zip = { version = "8.1", default-features = false, features = ["deflate-flate2"] }

[dev-dependencies]
tempfile = "3.10"
