//! Binds this client to the manifest `xtask` actually publishes.
//!
//! The producer (`xtask/src/manifest.rs`) and this reader mirror the schema by
//! hand across crate boundaries, so nothing but this fixture stops them
//! drifting. A rename on either side fails here or in the producer's
//! counterpart test — rather than shipping a manifest no client can parse,
//! which no per-crate test would catch.
//!
//! The fixture is generated by the producer's `#[ignore]`d regenerator, from
//! the real triple list and the real alias table, so it is the document a
//! release publishes: three engine archives resolved across six triples, plus
//! the two shared components.

use clonk_update::manifest::Manifest;

const FIXTURE: &str = include_str!("fixtures/manifest.json");

#[test]
fn the_client_parses_the_manifest_the_producer_emits() {
    let manifest = Manifest::parse(FIXTURE.as_bytes()).expect("client parses producer output");

    assert_eq!(manifest.version, "0.4.0");
    assert_eq!(manifest.engine_version, [4, 9, 11, 0, 362]);
    // Data first, executables last: an interrupted apply must leave an
    // older-but-working binary that can retry.
    let names: Vec<_> = manifest
        .components
        .iter()
        .map(|entry| entry.name.as_str())
        .collect();
    assert_eq!(names, ["content", "planet", "engine"]);
}

#[test]
fn every_build_resolves_to_its_own_archive() {
    let manifest = Manifest::parse(FIXTURE.as_bytes()).expect("parse");
    let engine = manifest
        .components
        .iter()
        .find(|entry| entry.name == "engine")
        .expect("engine entry");

    let linux = engine
        .target_for("x86_64-unknown-linux-gnu")
        .expect("linux target");
    let windows = engine
        .target_for("x86_64-pc-windows-msvc")
        .expect("windows target");
    let macos = engine
        .target_for("universal-apple-darwin")
        .expect("macos target");

    // The flaw this fixture exists to catch: a single `archive` field could not
    // express three per-build engine archives, so a client would fetch
    // whichever one happened to be recorded last.
    for other in [windows, macos] {
        assert_ne!(linux.archive, other.archive);
        assert_ne!(linux.sha256, other.sha256);
    }
    assert_ne!(windows.archive, macos.archive);
    // The engine archive already carries `bin/` or `Contents/`.
    assert!(linux.install.is_empty());
}

#[test]
fn a_mac_reporting_its_own_architecture_is_served_the_universal_build() {
    // macOS ships one universal `.app`, but a client can only report the triple
    // cargo compiled it for, so an already-updated Mac still asks for
    // `aarch64-apple-darwin` or `x86_64-apple-darwin`. Those keys are permanent:
    // if the manifest ever stopped carrying them, every Mac would be told there
    // is no update, for ever, with nothing to notice it.
    let manifest = Manifest::parse(FIXTURE.as_bytes()).expect("parse");
    let engine = manifest
        .components
        .iter()
        .find(|entry| entry.name == "engine")
        .expect("engine entry");

    let universal = engine
        .target_for("universal-apple-darwin")
        .expect("universal target");
    for triple in ["aarch64-apple-darwin", "x86_64-apple-darwin"] {
        let target = engine
            .target_for(triple)
            .unwrap_or_else(|| panic!("{triple} must still resolve"));
        // The whole target, not just the name: a client verifies the digest it
        // was handed, so an alias agreeing on the filename alone would fail at
        // the integrity check rather than at the manifest.
        assert_eq!(target, universal, "{triple} must get the universal build");
    }
}

#[test]
fn a_windows_gnu_client_is_served_the_msvc_build() {
    // The other alias, and the one that does drain: applying `engine` replaces
    // the executables wholesale, so a gnu install becomes an MSVC one and the
    // next check reports the new triple.
    let manifest = Manifest::parse(FIXTURE.as_bytes()).expect("parse");
    let engine = manifest
        .components
        .iter()
        .find(|entry| entry.name == "engine")
        .expect("engine entry");

    assert_eq!(
        engine.target_for("x86_64-pc-windows-gnu").expect("gnu"),
        engine.target_for("x86_64-pc-windows-msvc").expect("msvc")
    );
}

#[test]
fn a_shared_component_is_the_same_bytes_everywhere_it_lands() {
    let manifest = Manifest::parse(FIXTURE.as_bytes()).expect("parse");
    let content = manifest
        .components
        .iter()
        .find(|entry| entry.name == "content")
        .expect("content entry");

    let linux = content
        .target_for("x86_64-unknown-linux-gnu")
        .expect("linux");
    let macos = content.target_for("universal-apple-darwin").expect("macos");

    assert_eq!(linux.sha256, macos.sha256, "shared components must dedupe");
    assert_eq!(linux.archive, macos.archive);
    assert_eq!(linux.install, "content");
    assert_eq!(macos.install, "Contents/Resources/content");
}

#[test]
fn content_is_resolved_from_the_repository_that_publishes_it() {
    // `content.zip` is built and published where the game data lives, so the
    // producer records the release it came from. A client that dropped this
    // field would resolve the entry against a clonk-rs release that does not
    // carry the asset — a 404 behind a manifest that parses perfectly.
    let manifest = Manifest::parse(FIXTURE.as_bytes()).expect("parse");
    let content = manifest
        .components
        .iter()
        .find(|entry| entry.name == "content")
        .expect("content entry");

    for (triple, target) in &content.targets {
        let source = target
            .source
            .as_ref()
            .unwrap_or_else(|| panic!("content/{triple} must name its release"));
        assert_eq!(source.repo, "syb0rg/clonk-rs-content");
        assert!(source.tag.starts_with("content-"), "{}", source.tag);
        assert_eq!(target.archive, "content.zip");
    }

    // The mirror image: everything this repository builds omits the field, and
    // that absence is what routes it to the clonk-rs release.
    let engine = manifest
        .components
        .iter()
        .find(|entry| entry.name == "engine")
        .expect("engine entry");
    assert!(engine
        .targets
        .values()
        .all(|target| target.source.is_none()));
}

#[test]
fn every_shipped_triple_can_complete_an_install() {
    // A triple that resolves for one component but not another leaves a client
    // able to start an update it can never finish.
    let manifest = Manifest::parse(FIXTURE.as_bytes()).expect("parse");
    for triple in [
        "x86_64-unknown-linux-gnu",
        "x86_64-pc-windows-msvc",
        "x86_64-pc-windows-gnu",
        "universal-apple-darwin",
        "aarch64-apple-darwin",
        "x86_64-apple-darwin",
    ] {
        for name in ["content", "planet", "engine"] {
            let entry = manifest
                .components
                .iter()
                .find(|entry| entry.name == name)
                .unwrap_or_else(|| panic!("manifest has no `{name}` component"));
            assert!(
                entry.target_for(triple).is_some(),
                "{name} offers nothing to {triple}"
            );
        }
    }
}
