[package]
name = "clonk-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[features]
default = []

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
indexmap = "2"
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
