[package]
name = "clonk-audio"
version = "0.1.0"
edition = "2021"

[features]
default = ["cpal"]

[dependencies]
thiserror = "1"
hound = "3"
lewton = "0.10"
libloading = "0.8"
midly = { version = "=0.5.3", default-features = false, features = ["std", "strict"] }
minimp3 = "0.5"
cpal = { version = "0.18.1", optional = true }
tracing = "0.1"
