[package]
name = "clonk-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[features]
default = ["cpal"]

[dependencies]
thiserror = "1"
hound = "3"
lewton = "0.10"
libloading = "0.8"
midly = { version = "=0.5.3", default-features = false, features = ["std", "strict"] }
symphonia-bundle-mp3 = "0.6"
symphonia-core = "0.6"
cpal = { version = "0.18.1", optional = true }
tracing = "0.1"
