[workspace]
members = [
    "crates/lc-core",
    "crates/lc-resources",
    "crates/lc-script",
    "crates/lc-engine",
    "crates/lc-graphics",
    "crates/lc-frontend",
    "crates/lc-audio",
    "crates/lc-network",
    "crates/lc-gui",
    "crates/lc-platform",
    "crates/lc-app",
    "xtask",
]
resolver = "2"
