[package]
name = "lc-network"
version = "0.1.0"
edition = "2021"
autotests = false

[dependencies]
flate2 = "1"
iconv-native = "0.1"
lc-engine = { path = "../lc-engine" }
lc-resources = { path = "../lc-resources" }
serde = { version = "1", features = ["derive"] }
sha1 = "0.10"
thiserror = "1"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"] }
reqwest = { version = "0.12", default-features = false, features = ["cookies", "gzip", "rustls-tls"] }
socket2 = { version = "0.6", features = ["all"] }
xml-rs = "0.8"
[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tokio = { version = "1", features = ["test-util"] }

[[test]]
name = "integration"
path = "tests/main.rs"
