#!/usr/bin/env python3
"""Generate the shipped third-party license corpus.

The About dialog's Licenses page ships `COPYING` for this source tree. The
dependencies compiled into the shipped binaries carry their own terms, and most
of them require the license text to travel with the binary, so the text has to
be in the program rather than in a file somebody might not copy.

The corpus is generated rather than hand-maintained because it has to follow
the release graph exactly: a dependency added, removed or bumped changes what
must be attributed, and nobody notices a stale hand-written list until it is
wrong.

Run it after any dependency change:

    python3 scripts/generate_dependency_licenses.py

It needs the crate sources in the local Cargo registry, because the license
texts come from the packages themselves. `scripts/tests` verifies the checked-in
corpus against `Cargo.lock` without needing them.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import re
import subprocess
import sys

REPOSITORY = pathlib.Path(__file__).resolve().parent.parent
CORPUS = REPOSITORY / "crates/clonk-frontend/src/dependency_licenses.txt"

# The binaries a release actually ships. `xtask` is developer tooling and is
# deliberately not a root: its dependencies reach no user.
SHIPPED_BINARIES = frozenset(
    {"clonk-app", "clonk-c4group", "clonk-game", "clonk-launcher-shell"}
)

# What crates conventionally name the file carrying their terms.
LICENSE_FILE = re.compile(r"^(LICEN[CS]E|COPYING|NOTICE|UNLICENSE)", re.IGNORECASE)

HEADER = """\
Third-party licenses
====================

Clonk Rust links the packages listed below. Each section reproduces one
license text exactly as its authors distribute it, followed by every package
that section covers. Packages sharing an identical text share a section.

Generated by scripts/generate_dependency_licenses.py from the dependency graph
of the shipped binaries; do not edit by hand.
"""


def activated_dependencies(package: dict, features: list[str]) -> set[str]:
    """The optional dependencies a package's resolved features actually enable.

    An optional dependency is enabled by `dep:<name>`, by the implicit feature
    of the same name, or by a non-weak `<name>/<feature>` reference. A weak
    `<name>?/<feature>` enables nothing, yet still puts the package in the
    resolve graph: flate2's default `runtime_detection` carries `zlib-rs?/std`,
    so zlib-rs is an edge of a build that never compiles it.
    """
    table = package.get("features", {})
    # An implicit feature carries the name of the dependency it enables, so the
    # resolved feature names are candidates in their own right.
    activated = set(features)
    for feature in features:
        for value in table.get(feature, []):
            name, separator, _ = value.partition("/")
            if separator:
                if not name.endswith("?"):
                    activated.add(name)
            elif value.startswith("dep:"):
                activated.add(value.removeprefix("dep:"))
    return activated


def is_compiled_in(dependent: dict, activated: set[str], name: str) -> bool:
    """Whether an edge reaches the binary rather than only the resolve graph.

    Reads the dependent's manifest declarations, never the edge's target: the
    corpus deliberately covers every platform, so a Windows- or macOS-only
    package stays attributed on a Linux run.
    """
    declarations = [
        declaration
        for declaration in dependent["dependencies"]
        if declaration["name"] == name and declaration.get("kind") != "dev"
    ]
    if not declarations:
        # Nothing in the manifest explains the edge. Attribution errs towards
        # listing a package over dropping one the binary does link.
        return True
    if any(not declaration.get("optional") for declaration in declarations):
        return True
    return any(
        (declaration.get("rename") or declaration["name"]) in activated
        for declaration in declarations
    )


def release_graph(metadata: dict) -> list[dict]:
    """Every external package a shipped binary compiles in, non-dev only.

    Reachability in `resolve` is not enough: it also carries optional
    dependencies no activated feature enables, which no binary ever builds.
    """
    packages = {package["id"]: package for package in metadata["packages"]}
    root = metadata["workspace_root"]
    workspace = {
        package["id"]
        for package in metadata["packages"]
        if package["manifest_path"].startswith(root)
    }
    roots = [
        identifier
        for identifier in workspace
        if packages[identifier]["name"] in SHIPPED_BINARIES
    ]
    if len(roots) != len(SHIPPED_BINARIES):
        found = sorted(packages[identifier]["name"] for identifier in roots)
        raise SystemExit(f"expected every shipped binary in the workspace; found {found}")

    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    seen: set[str] = set()
    stack = list(roots)
    while stack:
        identifier = stack.pop()
        if identifier in seen:
            continue
        seen.add(identifier)
        dependent = packages[identifier]
        node = nodes[identifier]
        activated = activated_dependencies(dependent, node["features"])
        for dependency in node["deps"]:
            kinds = {kind.get("kind") for kind in dependency.get("dep_kinds", [])}
            # `None` is an ordinary dependency and "build" produces code that is
            # compiled in; only "dev" reaches no shipped binary.
            if kinds and kinds <= {"dev"}:
                continue
            name = packages[dependency["pkg"]]["name"]
            if not is_compiled_in(dependent, activated, name):
                continue
            stack.append(dependency["pkg"])

    return sorted(
        (packages[identifier] for identifier in seen if identifier not in workspace),
        key=lambda package: (package["name"], package["version"]),
    )


def license_texts(package: dict) -> list[tuple[str, str]]:
    """The (filename, text) pairs a package distributes, in a stable order."""
    source = pathlib.Path(package["manifest_path"]).parent
    try:
        entries = sorted(entry.name for entry in source.iterdir())
    except OSError:
        return []
    found = []
    for name in entries:
        if not LICENSE_FILE.match(name):
            continue
        path = source / name
        if not path.is_file():
            continue
        try:
            found.append((name, path.read_text(encoding="utf-8")))
        except UnicodeDecodeError:
            # A license nobody can read is not attribution; report it rather
            # than embedding replacement characters.
            raise SystemExit(f"{package['name']} {package['version']}: {name} is not UTF-8")
    return found


def render(packages: list[dict]) -> str:
    # Group by the exact bytes of each text, so a section appears once however
    # many packages ship it. 549 packages carry 4.3 MiB of text between them
    # and 909 KiB of distinct text; the duplication is not worth shipping.
    sections: dict[str, dict] = {}
    unlicensed: list[dict] = []
    for package in packages:
        texts = license_texts(package)
        if not texts:
            unlicensed.append(package)
            continue
        for name, text in texts:
            digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
            section = sections.setdefault(
                digest, {"filename": name, "text": text, "packages": []}
            )
            section["packages"].append(package)

    out = [HEADER]
    out.append(f"\nPackages: {len(packages)}\nSections: {len(sections)}\n")

    # Order by the first package each section covers, so the file is stable
    # across runs and a diff reads as "this dependency changed".
    ordered = sorted(
        sections.values(),
        key=lambda section: (
            section["packages"][0]["name"],
            section["packages"][0]["version"],
            section["filename"],
        ),
    )
    for section in ordered:
        out.append("\n" + "-" * 72 + "\n")
        covered = ", ".join(
            f"{package['name']} {package['version']}" for package in section["packages"]
        )
        out.append(f"Applies to: {covered}\n")
        out.append(f"Distributed as: {section['filename']}\n\n")
        out.append(section["text"].rstrip("\n") + "\n")

    if unlicensed:
        out.append("\n" + "-" * 72 + "\n")
        out.append(
            "The packages below declare their terms in package metadata but\n"
            "distribute no license file. Their SPDX expression is reproduced\n"
            "rather than a text they do not publish.\n\n"
        )
        for package in unlicensed:
            expression = package.get("license") or "no SPDX expression declared"
            out.append(f"{package['name']} {package['version']}: {expression}\n")

    return "".join(out)


def manifest(packages: list[dict]) -> str:
    """The (name, version, spdx) list, for the freshness check to compare."""
    lines = ["# Generated by scripts/generate_dependency_licenses.py; do not edit.\n"]
    for package in packages:
        expression = package.get("license") or ""
        lines.append(f"{package['name']}\t{package['version']}\t{expression}\n")
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in corpus is not what this would generate",
    )
    arguments = parser.parse_args()

    metadata = json.loads(
        subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--locked"],
            cwd=REPOSITORY,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    )
    packages = release_graph(metadata)
    corpus = render(packages)
    index = manifest(packages)
    index_path = CORPUS.with_suffix(".index")

    if arguments.check:
        stale = []
        for path, expected in ((CORPUS, corpus), (index_path, index)):
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual != expected:
                stale.append(path.relative_to(REPOSITORY))
        if stale:
            names = ", ".join(str(path) for path in stale)
            print(
                f"stale: {names}\nregenerate with "
                "`python3 scripts/generate_dependency_licenses.py`",
                file=sys.stderr,
            )
            return 1
        print(f"dependency licenses are current ({len(packages)} packages)")
        return 0

    CORPUS.write_text(corpus, encoding="utf-8")
    index_path.write_text(index, encoding="utf-8")
    print(
        f"wrote {CORPUS.relative_to(REPOSITORY)} "
        f"({len(corpus) / 1024:.0f} KiB, {len(packages)} packages)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
